name: DiffDRR
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pytorch>1.12
  - torchvision>0.5
  - cudatoolkit=11.3
  - pydicom
  - matplotlib
  - seaborn
  - black
  - flake8
  - ipykernel
  - tqdm
  - pip:
      - -e .  # Install the local package (DiffDRR)
